language: node_js
node_js:
- '8'
- '9'
cache: yarn
before_install:
- yarn global add greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
script:
- npm run ci
after_script:
- greenkeeper-lockfile-upload
after_success:
- npm run coverage:codecov
deploy:
  provider: npm
  skip_cleanup: true
  email: marcus.mennemeier@actano.de
  on:
    tags: true
    repo: actano/rplan-config
    node: '8'
  api_key:
    secure: jC0JO325C9v08/Aanag5aLBrmAg318o7dPFKhZo662MfwYqncFTkHduP7E5NeitRFYZhtBbVSuxLD2o2Ux0uJ8Y1Jjmqyas1IWeKAd4J/3k8xZBOxncmXjnhg23yYY0wFN+vOUA7kcpUOztxAqMrI4JJoF23aMRh/AlHbnXBKotAEbGDkdzl2NzSVg/lAtVCpTMJb3QYOQVfNnz2KdrX8/602rUO9dmcX1V1vk/JDjmo/OYEBD5X01+tFmWtJgqrKfCDl3Ca+71RAfYwqCKm7aaXQC78qQYaYCzsl+IUkQmg5i1GZQGLm6THW4qmY0cQA9Igfc7HbGbq7WRXNc/4y3qPF4PetYRLiFixM3hsipl/ZDmgDGyX33YrXfdj4FZO6Ulq7LrwPt4KTGpzpv4k9pMrhYeEQ7hzAWEP1bR5CrfG5BDNMigeLo7OOnrUzSHXL5SdPHwdzmUEzTCoBwi+OrSkPbZsh7D3RCDvaQQSe93BvxruLxYM8rENSlYGP0tiMBYQShaJlFahKpdXVBDBQ5h5QxQ536OSXIyCyc5O821FJEtxUQgUrDn/YlTvb/orquseTW8O2FWEnB3ETbXbv6TgwEjPrLakvXVzQmzx74AFb6PwEFYiQaR6ahvn0dmLJNaSYPi58A1Ngn0aSmp2k5aHEpwXJqYmHEvR1dRBcwg=
env:
  global:
    secure: dMS/6JYOnFc5gpUtq6nM0Xf7RsGV0oCyok+1u+et/1X9iCG0c6GLyuf00jq7AJDOb8cvsUViVG0qWdDIq3gvrgxaQ6qYAX8+QwyeQO7EZKqS6iRhRe3aBVQP6OUnv82nRmdFMviN4YTP6J7Fk9zXl7GtqrCDqt/zd6ov4jNaWypxUMhmbAzuQz396cO25IbXROFs9kLR4CoO8zJicbvkM6ODQG75lC5XSD5XSq3Xr0tHTZUEpC8ldZo72QexncHNk+njTAlRdXQS/EP+vnjrOjbLocylLzHLmw4Q/o/uJohPL2loZWa2PoEEeuktwsGuujNFq4CFZbYIj168sQYFDx52ILrRebhiHRGBTuxrW0e3+KRQXFi41pIQTQjO6Gpk1mfT/lvr1fd0/czK/islkUEo/W1+1PkdcIWvB65kXsxFKNfF0qhOz/ElZDodJCqEsBl3MMm0r5ilD0t+6HpJN5ME0dbwsNbgtbv+xUBxEyi+T2ypepILyPi+uiY4VuIUGChcbax6skNq+2B4+lAGVZ99td3JnaU0WDRBikL4o2TjiZERq6Lngq9hWo9S8MVSWyJXFP9Xrd+j88MjqJNAa1BVYjPXrGXr+Clg4jL8uyZ5+r6jUvI7C5zzaWJO1DoVThKWJvkjGr2tMdi2eZ/e4TULS/QO2XMEociWlTrGKAE=
